<a href="https://colab.research.google.com/github/akbarovyodgorbek931-hue/Yodgor1/blob/main/pandas_3_ipynd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [39]:
from google.colab import files
upload = files.upload()

Saving pandas_homework_dirty_data_2150_rows.csv to pandas_homework_dirty_data_2150_rows (1).csv

In [40]:
df=pd.read_csv("pandas_homework_dirty_data_2150_rows.csv")
df.head()

   order_id    shop  product     city amount   shop_date
0         1  Shop B   Laptop  Bukhara   3950  16.01.2025
1         2  Shop E   Laptop      NaN   1393         NaN
2         3     NaN  Monitor      NaN  1,200  17.09.2025
3         4     NaN      NaN  Bukhara   2456  21.01.2025
4         5     NaN   Laptop      NaN   4715  14.01.2025

In [46]:
df["shop"] = df["shop"].fillna("magazin")

In [41]:
df.head()

   order_id    shop  product     city amount   shop_date
0         1  Shop B   Laptop  Bukhara   3950  16.01.2025
1         2  Shop E   Laptop      NaN   1393         NaN
2         3     NaN  Monitor      NaN  1,200  17.09.2025
3         4     NaN      NaN  Bukhara   2456  21.01.2025
4         5     NaN   Laptop      NaN   4715  14.01.2025

In [48]:
df["shop_date"] = df["shop_date"].fillna(method="ffill")

/tmp/ipykernel_21665/3275954875.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["shop_date"] = df["shop_date"].fillna(method="ffill")

In [49]:
df["product"]=df['product'].fillna(method="ffill")

/tmp/ipykernel_21665/1495375374.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["product"]=df['product'].fillna(method="ffill")

In [51]:
df["city"]=df['city'].fillna(method="ffill")

/tmp/ipykernel_21665/1706882773.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["city"]=df['city'].fillna(method="ffill")

In [52]:
df.head()

   order_id     shop  product     city amount   shop_date
0         1   Shop B   Laptop  Bukhara   3950  16.01.2025
1         2   Shop E   Laptop  Bukhara   1393  16.01.2025
2         3  magazin  Monitor  Bukhara  1,200  17.09.2025
3         4  magazin  Monitor  Bukhara   2456  21.01.2025
4         5  magazin   Laptop  Bukhara   4715  14.01.2025